
version: "3"


services:
  backend:
    image: doc-test_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    deploy:
      replicas: 2
    environment:
      PLATEFORM: docker
      REDIS_HOST: http://redis
  frontend:
    image: doc-test_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  redis:
    image: redis