
version: "3"


services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    deploy:
      replicas: 2
    environment:
      PLATEFORM: docker
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
