
version: "3"


services:
  backend:
    image: doc-test_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    deploy:
      replicas: 10
    environment:
      PLATEFORM: docker
      REDIS_HOST: redis
      REDIS_PORT: 6379

  frontend:
    image: doc-test_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  redis:
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
